#!/usr/bin/env python3
"""Build VideoCaptioner CLI as a standalone executable using PyInstaller.

Usage:
    python scripts/build_exe.py          # build for current platform
    python scripts/build_exe.py --clean  # clean build

Prerequisites:
    pip install pyinstaller
    (all project dependencies must be installed in the current environment)

Output:
    dist/videocaptioner/  — the distributable folder
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
DIST_DIR = PROJECT_ROOT / "dist" / "videocaptioner"
SPEC_FILE = PROJECT_ROOT / "videocaptioner.spec"
RESOURCE_DIR = PROJECT_ROOT / "resource"
BUNDLED_FONTS = PROJECT_ROOT / "videocaptioner" / "resources" / "fonts"


def echo(msg: str) -> None:
    print(f"\033[1;34m==> {msg}\033[0m")


def run(cmd: list[str], **kwargs) -> None:
    echo(" ".join(cmd))
    subprocess.run(cmd, check=True, cwd=str(PROJECT_ROOT), **kwargs)


def build(args: argparse.Namespace) -> int:
    # 1. Check PyInstaller
    if not shutil.which("pyinstaller"):
        echo("Installing PyInstaller...")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "pyinstaller"],
            check=True,
        )

    # 2. Clean
    if args.clean:
        echo("Cleaning previous build...")
        for p in [PROJECT_ROOT / "build", DIST_DIR.parent / "videocaptioner"]:
            if p.exists():
                shutil.rmtree(p)

    # 3. Ensure _version.py exists (generated by hatch-vcs in normal builds)
    version_file = PROJECT_ROOT / "videocaptioner" / "_version.py"
    if args.version:
        echo(f"Writing version: {args.version}")
        version_file.write_text(
            f'__version__ = "{args.version}"  # PyInstaller build\n',
            encoding="utf-8",
        )
    elif not version_file.exists():
        echo("Generating _version.py (placeholder)...")
        version_file.write_text(
            '__version__ = "0.0.0"  # placeholder for PyInstaller build\n',
            encoding="utf-8",
        )

    # 4. Run PyInstaller
    echo("Running PyInstaller...")
    run(["pyinstaller", str(SPEC_FILE), "--noconfirm"])

    # 5. Suppress GUI-mode auto-launch (remove .ui modules from bundle if present)
    # PyInstaller --excludes should handle this, but belt-and-suspenders:
    for ui_dir in [
        DIST_DIR / "videocaptioner" / "ui",
        DIST_DIR / "PyQt5",
        DIST_DIR / "qfluentwidgets",
    ]:
        if ui_dir.exists():
            shutil.rmtree(ui_dir)

    # 6. Copy resource/ into dist (fonts, styles, assets)
    echo("Copying resource files...")
    for subdir in ["fonts", "subtitle_style"]:
        src = RESOURCE_DIR / subdir
        dst = DIST_DIR / "resource" / subdir
        if src.exists():
            dst.mkdir(parents=True, exist_ok=True)
            for f in src.iterdir():
                if f.is_file():
                    shutil.copy2(f, dst / f.name)

    # 7. Create bin/ directory
    bin_dir = DIST_DIR / "resource" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    # 8. Write bin README
    readme = bin_dir / "README.txt"
    readme.write_text(
        "Place external executables here so VideoCaptioner can find them:\n\n"
        "Required:\n"
        "  ffmpeg.exe       — Audio extraction, video encoding, subtitle burning\n"
        "                     Download: https://ffmpeg.org/download.html\n\n"
        "Optional:\n"
        "  yt-dlp.exe       — Download videos from YouTube, Bilibili, etc.\n"
        "                     (also usable as 'download' command without exe)\n\n"
        "  whisper-cpp.exe  — Local ASR (--asr whisper-cpp)\n"
        "                     Download from: https://github.com/ggerganov/whisper.cpp\n\n"
        "  faster-whisper-xxl.exe — Local ASR (--asr whisper-cpp, faster variant)\n"
        "                     Download from the GUI or:\n"
        "                     https://github.com/Purfview/whisper-standalone-win\n\n"
        "These binaries are NOT required for bijian/jianying ASR (free, built-in)\n"
        "or for LLM-based optimization/translation.\n",
        encoding="utf-8",
    )

    # 9. Untrack bundled fonts from config (use resource/fonts instead)
    bundled = DIST_DIR / "videocaptioner" / "resources" / "fonts"
    if bundled.exists():
        shutil.rmtree(DIST_DIR / "videocaptioner" / "resources")

    # 10. Summary
    echo(f"Build complete: {DIST_DIR.resolve()}")
    exe = DIST_DIR / "videocaptioner.exe"
    if exe.exists():
        size_mb = sum(f.stat().st_size for f in DIST_DIR.rglob("*") if f.is_file()) / (1024 * 1024)
        echo(f"Executable: {exe.name} ({size_mb:.0f} MB total)")
    else:
        exe = DIST_DIR / "videocaptioner"
        if exe.exists():
            size_mb = sum(f.stat().st_size for f in DIST_DIR.rglob("*") if f.is_file()) / (1024 * 1024)
            echo(f"Executable: {exe.name} ({size_mb:.0f} MB total)")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build VideoCaptioner standalone executable")
    parser.add_argument("--clean", action="store_true", help="Clean build directory first")
    parser.add_argument("--version", metavar="VER", help="Version string for the build (e.g. 1.5.0)")
    args = parser.parse_args()
    return build(args)


if __name__ == "__main__":
    sys.exit(main())
